version: '3'

services:
  redis:
    container_name: redis
    image: redis:4.0.11
    command: redis-server --requirepass $REDIS_PASSWORD
    ports:
      - "6379:6379"
    volumes:
      - ./redisdb/:/data
    restart: always
    env_file: ./.env