version: '3'
services:

  auth_db:
    container_name:  postgres-auth-db
    image:           postgres
    ports:
      - 5433:5432 # Bind host port 5432 to PostgreSQL port 5432
    restart: always
    volumes:
      - ../auth-db-data:/var/lib/postgresql/data
    env_file: ../.env
    environment:
      - LC_ALL=C.UTF-8

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080